micronaut:
  application:
    name: updateoperatorsDemo
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb

rewards:
  minimumAmount: "100.00"
  minimumPurchaseDays: 3
